[View in Colaboratory](https://colab.research.google.com/github/schwaaweb/aimlds1_05/blob/master/M05_CC--Statistics_Coding_Challenge_1.ipynb)

# Statistics Coding Challenge #1

In this coding challenge, we are going to use the "Accidental Drug Related Deaths 2012-2017 (State of Connecticut)" data set available from the Data.Gov website (https://catalog.data.gov/dataset?groups=local&organization_type=State+Government#topic=local_navigation). 

There are 2 main objectives you need to accomplish:

1) First treat missing values for the "Death City" attribute - replace any missing values in the "Death City" with the city that has experienced the most number of deaths

For each city, do the following:

2) Compute summary statistics for the *age* attribute:


a) Mean

b) Median

c) 25%, 50% and 75% percentiles using [np.percentile](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.percentile.html)

d) Examine any outliers in data using [Boxplots](https://matplotlib.org/2.1.1/gallery/statistics/boxplot_demo.html)

e) Construct a Bee Swarm plot to highlight the distibution of age by each city using [seaborn.swarmplot](https://seaborn.pydata.org/generated/seaborn.swarmplot.html)

In [1]:
# LAMBDA SCHOOL
#
# MACHINE LEARNING
#
# MIT LICENSE

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('Accidental_Drug_Related_Deaths__2012-2017.csv')

In [4]:
np.shape(data)

(4083, 32)

In [13]:
data.iloc[0]

CaseNumber                                            14-9876
Date                                               06/28/2014
Sex                                                       NaN
Race                                                      NaN
Age                                                       NaN
Residence City                                            NaN
Residence State                                           NaN
Residence County                                          NaN
Death City                                                NaN
Death State                                               NaN
Death County                                              NaN
Location                                                  NaN
DescriptionofInjury                                       NaN
InjuryPlace                                               NaN
ImmediateCauseA          Acute fent, hydrocod, benzodiazepine
Heroin                                                    NaN
Cocaine                                                   NaN
Fentanyl                                                    Y
Oxycodone                                                 NaN
Oxymorphone                                               NaN
EtOH                                                      NaN
Hydrocodone                                                 Y
Benzodiazepine                                              Y
Methadone                                                 NaN
Amphet                                                    NaN
Tramad                                                    NaN
Morphine (not heroin)                                     NaN
Other                                                     NaN
Any Opioid                                                NaN
MannerofDeath                                        Accident
AmendedMannerofDeath                                      NaN
DeathLoc                          CT\n(41.544654, -72.651713)
Name: 0, dtype: object

In [21]:
print(data.InjuryPlace.unique().size)

68

In [45]:

data['Death City'].value_counts().head()

HARTFORD       428
NEW HAVEN      303
WATERBURY      283
BRIDGEPORT     271
NEW BRITAIN    169
Name: Death City, dtype: int64

In [46]:
data['Death City'].value_counts().index[0]

'HARTFORD'

In [49]:
data = data.fillna(data['Death City'].value_counts().index[0])

In [52]:
data['Death City'].isna().sum()

0

In [53]:
data['Death City'].value_counts().head()

HARTFORD       432
NEW HAVEN      303
WATERBURY      283
BRIDGEPORT     271
NEW BRITAIN    169
Name: Death City, dtype: int64

In [58]:
data.groupby( [ "Death City", "Age"] ).count()

                    CaseNumber  Date  Sex  Race  Residence City  \
Death City    Age
6340          51.0           1     1    1     1               1
AMSTON        32.0           1     1    1     1               1
ANDOVER       34.0           1     1    1     1               1
              49.0           1     1    1     1               1
ANSONIA       23.0           1     1    1     1               1
              24.0           1     1    1     1               1
              27.0           1     1    1     1               1
              28.0           1     1    1     1               1
              30.0           1     1    1     1               1
              33.0           1     1    1     1               1
              35.0           1     1    1     1               1
              36.0           1     1    1     1               1
              39.0           1     1    1     1               1
              42.0           1     1    1     1               1
              43.0           1     1    1     1               1
              44.0           1     1    1     1               1
              47.0           1     1    1     1               1
              48.0           1     1    1     1               1
              51.0           1     1    1     1               1
              53.0           2     2    2     2               2
              57.0           1     1    1     1               1
              59.0           1     1    1     1               1
              63.0           1     1    1     1               1
ASHFORD       29.0           1     1    1     1               1
              30.0           1     1    1     1               1
              31.0           1     1    1     1               1
              36.0           1     1    1     1               1
              48.0           1     1    1     1               1
AVON          20.0           1     1    1     1               1
              25.0           1     1    1     1               1
...                        ...   ...  ...   ...             ...
WINDSOR LOCKS 25.0           2     2    2     2               2
              27.0           1     1    1     1               1
              29.0           1     1    1     1               1
              30.0           1     1    1     1               1
              32.0           1     1    1     1               1
              37.0           1     1    1     1               1
              46.0           1     1    1     1               1
              48.0           1     1    1     1               1
              49.0           1     1    1     1               1
              53.0           1     1    1     1               1
              54.0           1     1    1     1               1
              57.0           1     1    1     1               1
              59.0           1     1    1     1               1
WINSTED       24.0           2     2    2     2               2
              27.0           1     1    1     1               1
              33.0           1     1    1     1               1
              35.0           1     1    1     1               1
              36.0           1     1    1     1               1
              40.0           1     1    1     1               1
              44.0           1     1    1     1               1
              51.0           2     2    2     2               2
WOODBRIDGE    22.0           1     1    1     1               1
              27.0           1     1    1     1               1
              29.0           1     1    1     1               1
              58.0           1     1    1     1               1
WOODBURY      29.0           1     1    1     1               1
              49.0           1     1    1     1               1
WOODSTOCK     31.0           1     1    1     1               1
              42.0           1     1    1     1               1
              54.0           1     1    1     1               1

                    Residence State  Residence County  Death State  \
Death City    Age
6340          51.0                1                 1            1
AMSTON        32.0                1                 1            1
ANDOVER       34.0                1                 1            1
              49.0                1                 1            1
ANSONIA       23.0                1                 1            1
              24.0                1                 1            1
              27.0                1                 1            1
              28.0                1                 1            1
              30.0                1                 1            1
              33.0                1                 1            1
              35.0                1                 1            1
              36.0                1                 1            1
              39.0                1                 1            1
              42.0                1                 1            1
              43.0                1                 1            1
              44.0                1                 1            1
              47.0                1                 1            1
              48.0                1                 1            1
              51.0                1                 1            1
              53.0                2                 2            2
              57.0                1                 1            1
              59.0                1                 1            1
              63.0                1                 1            1
ASHFORD       29.0                1                 1            1
              30.0                1                 1            1
              31.0                1                 1            1
              36.0                1                 1            1
              48.0                1                 1            1
AVON          20.0                1                 1            1
              25.0                1                 1            1
...                             ...               ...          ...
WINDSOR LOCKS 25.0                2                 2            2
              27.0                1                 1            1
              29.0                1                 1            1
              30.0                1                 1            1
              32.0                1                 1            1
              37.0                1                 1            1
              46.0                1                 1            1
              48.0                1                 1            1
              49.0                1                 1            1
              53.0                1                 1            1
              54.0                1                 1            1
              57.0                1                 1            1
              59.0                1                 1            1
WINSTED       24.0                2                 2            2
              27.0                1                 1            1
              33.0                1                 1            1
              35.0                1                 1            1
              36.0                1                 1            1
              40.0                1                 1            1
              44.0                1                 1            1
              51.0                2                 2            2
WOODBRIDGE    22.0                1                 1            1
              27.0                1                 1            1
              29.0                1                 1            1
              58.0                1                 1            1
WOODBURY      29.0                1                 1            1
              49.0                1                 1            1
WOODSTOCK     31.0                1                 1            1
              42.0                1                 1            1
              54.0                1                 1            1

                    Death County  Location    ...     Benzodiazepine  \
Death City    Age                             ...
6340          51.0             1         1    ...                  1
AMSTON        32.0             1         1    ...                  1
ANDOVER       34.0             1         1    ...                  1
              49.0             1         1    ...                  1
ANSONIA       23.0             1         1    ...                  1
              24.0             1         1    ...                  1
              27.0             1         1    ...                  1
              28.0             1         1    ...                  1
              30.0             1         1    ...                  1
              33.0             1         1    ...                  1
              35.0             1         1    ...                  1
              36.0             1         1    ...                  1
              39.0             1         1    ...                  1
              42.0             1         1    ...                  1
              43.0             1         1    ...                  1
              44.0             1         1    ...                  1
              47.0             1         1    ...                  1
              48.0             1         1    ...                  1
              51.0             1         1    ...                  1
              53.0             2         2    ...                  2
              57.0             1         1    ...                  1
              59.0             1         1    ...                  1
              63.0             1         1    ...                  1
ASHFORD       29.0             1         1    ...                  1
              30.0             1         1    ...                  1
              31.0             1         1    ...                  1
              36.0             1         1    ...                  1
              48.0             1         1    ...                  1
AVON          20.0             1         1    ...                  1
              25.0             1         1    ...                  1
...                          ...       ...    ...                ...
WINDSOR LOCKS 25.0             2         2    ...                  2
              27.0             1         1    ...                  1
              29.0             1         1    ...                  1
              30.0             1         1    ...                  1
              32.0             1         1    ...                  1
              37.0             1         1    ...                  1
              46.0             1         1    ...                  1
              48.0             1         1    ...                  1
              49.0             1         1    ...                  1
              53.0             1         1    ...                  1
              54.0             1         1    ...                  1
              57.0             1         1    ...                  1
              59.0             1         1    ...                  1
WINSTED       24.0             2         2    ...                  2
              27.0             1         1    ...                  1
              33.0             1         1    ...                  1
              35.0             1         1    ...                  1
              36.0             1         1    ...                  1
              40.0             1         1    ...                  1
              44.0             1         1    ...                  1
              51.0             2         2    ...                  2
WOODBRIDGE    22.0             1         1    ...                  1
              27.0             1         1    ...                  1
              29.0             1         1    ...                  1
              58.0             1         1    ...                  1
WOODBURY      29.0             1         1    ...                  1
              49.0             1         1    ...                  1
WOODSTOCK     31.0             1         1    ...                  1
              42.0             1         1    ...                  1
              54.0             1         1    ...                  1

                    Methadone  Amphet  Tramad  Morphine (not heroin)  Other  \
Death City    Age
6340          51.0          1       1       1                      1      1
AMSTON        32.0          1       1       1                      1      1
ANDOVER       34.0          1       1       1                      1      1
              49.0          1       1       1                      1      1
ANSONIA       23.0          1       1       1                      1      1
              24.0          1       1       1                      1      1
              27.0          1       1       1                      1      1
              28.0          1       1       1                      1      1
              30.0          1       1       1                      1      1
              33.0          1       1       1                      1      1
              35.0          1       1       1                      1      1
              36.0          1       1       1                      1      1
              39.0          1       1       1                      1      1
              42.0          1       1       1                      1      1
              43.0          1       1       1                      1      1
              44.0          1       1       1                      1      1
              47.0          1       1       1                      1      1
              48.0          1       1       1                      1      1
              51.0          1       1       1                      1      1
              53.0          2       2       2                      2      2
              57.0          1       1       1                      1      1
              59.0          1       1       1                      1      1
              63.0          1       1       1                      1      1
ASHFORD       29.0          1       1       1                      1      1
              30.0          1       1       1                      1      1
              31.0          1       1       1                      1      1
              36.0          1       1       1                      1      1
              48.0          1       1       1                      1      1
AVON          20.0          1       1       1                      1      1
              25.0          1       1       1                      1      1
...                       ...     ...     ...                    ...    ...
WINDSOR LOCKS 25.0          2       2       2                      2      2
              27.0          1       1       1                      1      1
              29.0          1       1       1                      1      1
              30.0          1       1       1                      1      1
              32.0          1       1       1                      1      1
              37.0          1       1       1                      1      1
              46.0          1       1       1                      1      1
              48.0          1       1       1                      1      1
              49.0          1       1       1                      1      1
              53.0          1       1       1                      1      1
              54.0          1       1       1                      1      1
              57.0          1       1       1                      1      1
              59.0          1       1       1                      1      1
WINSTED       24.0          2       2       2                      2      2
              27.0          1       1       1                      1      1
              33.0          1       1       1                      1      1
              35.0          1       1       1                      1      1
              36.0          1       1       1                      1      1
              40.0          1       1       1                      1      1
              44.0          1       1       1                      1      1
              51.0          2       2       2                      2      2
WOODBRIDGE    22.0          1       1       1                      1      1
              27.0          1       1       1                      1      1
              29.0          1       1       1                      1      1
              58.0          1       1       1                      1      1
WOODBURY      29.0          1       1       1                      1      1
              49.0          1       1       1                      1      1
WOODSTOCK     31.0          1       1       1                      1      1
              42.0          1       1       1                      1      1
              54.0          1       1       1                      1      1

                    Any Opioid  MannerofDeath  AmendedMannerofDeath  DeathLoc
Death City    Age
6340          51.0           1              1                     1         1
AMSTON        32.0           1              1                     1         1
ANDOVER       34.0           1              1                     1         1
              49.0           1              1                     1         1
ANSONIA       23.0           1              1                     1         1
              24.0           1              1                     1         1
              27.0           1              1                     1         1
              28.0           1              1                     1         1
              30.0           1              1                     1         1
              33.0           1              1                     1         1
              35.0           1              1                     1         1
              36.0           1              1                     1         1
              39.0           1              1                     1         1
              42.0           1              1                     1         1
              43.0           1              1                     1         1
              44.0           1              1                     1         1
              47.0           1              1                     1         1
              48.0           1              1                     1         1
              51.0           1              1                     1         1
              53.0           2              2                     2         2
              57.0           1              1                     1         1
              59.0           1              1                     1         1
              63.0           1              1                     1         1
ASHFORD       29.0           1              1                     1         1
              30.0           1              1                     1         1
              31.0           1              1                     1         1
              36.0           1              1                     1         1
              48.0           1              1                     1         1
AVON          20.0           1              1                     1         1
              25.0           1              1                     1         1
...                        ...            ...                   ...       ...
WINDSOR LOCKS 25.0           2              2                     2         2
              27.0           1              1                     1         1
              29.0           1              1                     1         1